# Generated by Django 5.0.3 on 2025-02-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devloper', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='humanResources',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
